### ISSUE TITLE
[ADD FEATURE]: While the link is being shortened, the loading indicator should be displayed.

### ISSUE THREAD

**Issue by Michael-Obele** [unnikrishnan2002/Narrow-Links#14]
The loading indication should be displayed while the link is being shortened. To notify the user that a click has been initiated and the link has been shortened. To avoid repetitive tries or the perception that the action is inactive.

**Comment by unnikrishnan2002** [comment]
Great call ! You would like to work on this ? @Michael-Obele

**Comment by Michael-Obele** [comment]
Yes, however, for the time being, I've included the text loading to the shortened text result bar.
