### ISSUE TITLE
Bug - Check for Invalid URL

### ISSUE THREAD

**Issue by Villain45** [unnikrishnan2002/Narrow-Links#26]
The input is not checking for a valid URL, whatever the user type it considers that as an URL, so first we have to check it is a valid URL or not...

I found this bug and would like to work on it
Add hacktoberfest tag

**Comment by unnikrishnan2002** [comment]
Great catch !! You can work on it @Villain45

**Comment by diviprakashpc** [comment]
Hii Can i work on this issue? I am thinking of using react-bootstrap or some regular expression pattern matching to validate the url. If it is invalid I would be showing an error message .

**Comment by unnikrishnan2002** [comment]
@diviprakashpc this issue is already assigned. More issues will be coming

**Comment by Villain45** [comment]
Had many conflicts for the earlier one.....will update this issue soon

**Comment by Yasshu55** [comment]
@Villain45 It's already been 11 Days since we assigned this issue to you and it hasn't been solved yet...the issue has been unsolved for too long so we are assigning this issue to another person.

btw Good try!

**Comment by Villain45** [comment]
@Yasshu55 Did u read my previous comment? before 2 days one
The previous PR had many conflicts, so i was updating it

Fine with your decision, nvm

**Comment by Villain45** [comment]
@Yasshu55 if u want still i can fix that, left to your decision bro

**Comment by Yasshu55** [comment]
Yes @Villain45 I've seen your previous comment but its already been 2 days.....well if you are confident that you can complete it within the next 2 days then I can reassign it to you...because it has already been 11+ days for a good-first-issue

**Comment by Villain45** [comment]
@Yasshu55 Sure
