### ISSUE TITLE
Show the QR code in a modal instead of new tab

### ISSUE THREAD

**Issue by unnikrishnan2002** [unnikrishnan2002/Narrow-Links#30]
Currently , when the user clicks on the QR code icon it takes the user to a new tab. We need a modal, similar to the modal of the `send linke as SMS` function and display the QR code in that modal in the same page only

**Comment by najeebkp** [comment]
Hey @unnikrishnan2002  please assign this to me

**Comment by unnikrishnan2002** [comment]
Go ahead @najeebkp
