### ISSUE TITLE
Add templates for better maintaining

### ISSUE THREAD

**Issue by Dun-sin** [unnikrishnan2002/Narrow-Links#33]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes it easier for you to maintain your projects.

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

**Comment by unnikrishnan2002** [comment]
Are you willing to do it @Dun-sin ?

**Comment by Dun-sin** [comment]
> Are you willing to do it @Dun-sin ?

anyone can

**Comment by unnikrishnan2002** [comment]
> > Are you willing to do it @Dun-sin ?
> 
> anyone can

I mean do you want to work on it ? I can assign you then

**Comment by Dun-sin** [comment]
> > > Are you willing to do it @Dun-sin ?
> > 
> > 
> > anyone can
> 
> I mean do you want to work on it ? I can assign you then

Yeah, I got that, I'm saying anyone else can, I don't want it

**Comment by unnikrishnan2002** [comment]
Sure

**Comment by rsk2** [comment]
Hi @unnikrishnan2002, can I work on this?

**Comment by unnikrishnan2002** [comment]
Go ahead @rsk2

**Comment by rsk2** [comment]
Can we close this issue?
