### ISSUE TITLE
Simple & Neat NarrowLinks Front-End Design 🎨

### ISSUE THREAD

**Issue by gnwncpta** [unnikrishnan2002/Narrow-Links#38]
### Hi 🖐, I came up with this design idea, style & layout.
After trying **NarrowLinks** app and got the understanding of the flow now i can show you my design that i made for **NarrowLinks**.
I also made responsive design for mobile so we together may have the imaginary of how if the app on mobile phone looks like. I also made simple logo for the app so because users will have the identity that will stick on their mind.

So here's the design and with some explanation:

**Link:** [Figma Design](https://www.figma.com/file/GGkebbJ4rTDfgFGNgXd2r4/Narrow-Links?node-id=0%3A1)

### **♦ Idle State**
<img src="https://i.imgur.com/8bcpxMP.png" />

### **📮 Explanation:** 
When the user is the first time opening the app on desktop it will look like this. Okay, you might be asking why the login button have the **auth0** icon, right ? It's because we have to give user an information that the login is just for **auth0** authentication, not for user to manage their links that they made before. You got it ? okay good.

<br/>
<br/>

### **♦ Creating URL State**
<img src="https://i.imgur.com/GC0Pzwd.png" />

### **📮 Explanation:** 
There's not much different from before, It's just when the user paste their link and click Shorten purple button, The app will give the user an information that the links is being generated at the moment.

<br/>
<br/>

### **♦ Result State**
<img src="https://i.imgur.com/Smc5lMm.png" />

### **📮 Explanation:** 
After the generated process is done, then the app will give the shortened url to the user. 
Okay you might be asking again, why i grouping the shortened link and the share buttons like that ? It's because the shortened link and the buttons have a connection between them. So when you see the result like that the user will think that the shortened link is shareable via SMS and QR code. That's it

Why the Show QR button have purple color ? So when user's cursor is hovering on the buttons, the button background color will change to purple color.

### So yeah thats the design that i made 😁
If you have any thoughts or any question you can tell me, Thanks
If you don't mind, let me do the front end work because i know about the design and i can do layouting.

**Comment by Yasshu55** [comment]
Hey @gnwncpta , There's already an issue opened on this aspect. Comment your design and explanation over here [ Issue- #20 ]

**Comment by gnwncpta** [comment]
pardon me @Yasshu55 i was on that issue-#20 but i clicked the New Issue button where i think it will comment on the issue 😁

**Comment by gnwncpta** [comment]
Yeah thanks for the feedback 😁
