### ISSUE TITLE
Make UI responsive 

### ISSUE THREAD

**Issue by sri-rishi** [unnikrishnan2002/Narrow-Links#44]
Currently this is how UI looks in smaller screen 

![image](https://user-images.githubusercontent.com/72429483/195970487-8f7aa4fc-c7e3-4270-8a1d-604e4b9e608d.png)

I want to make UI better in smaller screen, can you assign me this issue

**Comment by unnikrishnan2002** [comment]
Hey @sri-rishi We are going to redesign the website, so there is no point in making this Ui responsive. Will be opening more issues, keep an eye on that
