### ISSUE TITLE
Alert message during login!

### ISSUE THREAD

**Issue by Savio629** [unnikrishnan2002/Narrow-Links#46]
There's a popup of alert message during login.

Cause : One or more Social Connections are using the Auth0 dev keys.

Solution : Need to go to the [social connections ](https://manage.auth0.com/#/connections/social) in the dashboard of Auth0 , select each social connection, and then check if you left any of the API Key and Secret Key empty. If so, you’re using the Auth0 dev keys and will need to configure them with social connection dev keys.
@unnikrishnan2002

**Comment by unnikrishnan2002** [comment]
Will look into that ! Thanks
