### ISSUE TITLE
[BUG] detecting http and https url

### ISSUE THREAD

**Issue by abhijain2003** [unnikrishnan2002/Narrow-Links#59]
### Description

Hey I wanted to work on detecting this project adding functionality to throw error when user enter wrong url

please assign this to me under hacktoberfest

### Steps to reproduce the problem

when user click on shorten button so, before the process begins of shorterning I will apply a condition to check if url string's first 4 or 5 characters are equal to http or https or not

if yes then, will continue the process
else through error that url is wrong

### Screenshots

![Screenshot 2022-10-24 144425](https://user-images.githubusercontent.com/91718608/197491423-32a732b2-c700-4e96-b645-e4ede01fae63.png)

**Comment by Yasshu55** [comment]
@abhijain2003 So along with throwing the error I would suggest showing a Toast message saying that the URL is Invalid.
Can you do it?

**Comment by abhijain2003** [comment]
can I use this https://www.npmjs.com/package/react-toastify package
